feat: separating between mech and requester activity checker
valory-xyz/autonolas-staking-programmes pull request #26
Opened 2024-08-26 12:08 UTC by kupermind

- Separating between mech and requester activity checker.

2024-08-26 12:11 UTC, 77ph approved these changes

2024-08-27 20:35 UTC, kupermind commented on contracts/mech_usage/MechActivityChecker.sol
> +    address public immutable mechMarketplace;
Mech marketplace is used here as well.

2024-08-27 20:36 UTC, kupermind commented on contracts/mech_usage/MechActivityChecker.sol
> +        nonces[1] = IMechMarketplace(mechMarketplace).getOperatorDeliveriesCount(multisig);
We care about the mech operator deliveries, not about the mech itself (that could be more than one or swapped).

2024-08-28 09:32 UTC, DavidMinarsch requested changes

2024-08-28 09:32 UTC, DavidMinarsch commented on contracts/mech_usage/MechActivityChecker.sol
> +    function getOperatorDeliveriesCount(address operator) external view returns (uint256);
Operator is annoying here. I'd say "Service" because Operator has another use in Olas.

2024-08-28 09:32 UTC, DavidMinarsch commented on contracts/mech_usage/RequesterActivityChecker.sol
> +    /// @dev Checks if the service multisig liveness ratio passes the defined liveness threshold.
Same as in MechActivityChecker?

2024-08-28 12:30 UTC, 77ph approved these changes

2024-08-28 14:37 UTC, merged